@id=0192624897-d079-431b-a5c1-2c527647f3c9

PUT http://localhost:5287/api/{{id}}
Content-Type: application/json

{
    "name": "Joel Deon Dsouza",
    "description": "In publishing and graphic design, Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface without relying on meaningful content.",
    "startDateTime": "2023-07-23T09:00:00",
    "endDateTime": "2023-07-23T10:00:00",
}